name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  EC2_USER: ubuntu
  APP_DIR: /opt/devops-blog
  TERRAFORM_DIR: ./terraform/docker-compose-ec2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ---------- Checkout code ----------
    - name: Checkout repository
      uses: actions/checkout@v3

    # ---------- Set up SSH key ----------
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/devops-key
        chmod 600 ~/.ssh/devops-key

    # ---------- Configure AWS ----------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: List Terraform folder
      run: ls -la ./terraform/docker-compose-ec2

    # ---------- Configure Terraform ----------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.13.4

    - name: Verify working directory
      run: pwd && ls -la ./terraform/docker-compose-ec2

    - name: Check Terraform version
      run: terraform version
    
    # ---------- Authenticate Terraform Cloud ----------
    - name: Authenticate to Terraform Cloud
      run: |
        mkdir -p ~/.terraform.d
        cat > ~/.terraform.d/credentials.tfrc.json <<EOF
        {
          "credentials": {
            "app.terraform.io": {
              "token": "${{ secrets.TF_API_TOKEN }}"
            }
          }
        }
        EOF

    # ---------- Terraform Init & Apply ----------
    - name: Terraform Init
      env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      run: terraform -chdir=./terraform/docker-compose-ec2 init

    - name: Terraform Apply
      run: terraform -chdir=./terraform/docker-compose-ec2 apply -auto-approve
      env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        TF_VAR_region: ${{ vars.REGION }}
        TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        TF_VAR_mongo_uri: ${{ secrets.MONGO_URI }}
        TF_VAR_PORT: ${{ vars.PORT }}
        TF_VAR_devops_public_key: ${{ secrets.devops_public_key }}


    # ---------- Get EC2 Public IP ----------
    - name: Get EC2 public IP
      id: get-ec2-ip
      run: |
        EC2_IP=$(terraform -chdir=./terraform/docker-compose-ec2 output -raw public_ip 2>/dev/null | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n1)
        echo "ec2_ip=$EC2_IP" >> $GITHUB_OUTPUT
        echo "✅ EC2 Public IP: $EC2_IP"

    # ---------- Wait for EC2 to be Ready ----------
    - name: Wait for EC2 SSH
      run: |
        echo "Waiting for EC2 instance to be ready..."
        for i in {1..10}; do
          if ssh -o StrictHostKeyChecking=no -i ~/.ssh/devops-key ubuntu@${{ steps.get-ec2-ip.outputs.ec2_ip }} "echo 'Instance is ready'" 2>/dev/null; then
            echo "✅ EC2 is ready for SSH"
            exit 0
          fi
          echo "Attempt $i: still waiting..."
          sleep 10
        done
        echo "❌ EC2 did not become ready in time"
        exit 1

    # ---------- Wait for Docker Setup to complete ----------
    - name: Wait for Docker setup to complete
      run: |
        echo "⏳ Waiting for EC2 cloud-init to finish..."
        for i in {1..20}; do
          if ssh -o StrictHostKeyChecking=no -i ~/.ssh/devops-key ubuntu@${{ steps.get-ec2-ip.outputs.ec2_ip }} "cloud-init status --wait" 2>/dev/null; then
            echo "✅ Docker Setup completed"
            exit 0
          fi
          echo "Attempt $i: still waiting..."
          sleep 15
        done
        echo "❌ Cloud-init did not finish in time"
        exit 1

    # ---------- Deploy to EC2 ----------
    - name: Deploy app to EC2
      run: |
        echo "Deploying to ${{ steps.get-ec2-ip.outputs.ec2_ip }}"

        # Ensure target directory exists
        ssh -i ~/.ssh/devops-key -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ steps.get-ec2-ip.outputs.ec2_ip }} "sudo mkdir -p ${APP_DIR} && sudo chown -R ${{ env.EC2_USER }}:${{ env.EC2_USER }} ${APP_DIR}"

        # Copy repo to EC2
        rsync -avz -e "ssh -i ~/.ssh/devops-key -o StrictHostKeyChecking=no" \
        --exclude '.git' \
        --exclude '.github' \
        ./ ${{ env.EC2_USER }}@${{ steps.get-ec2-ip.outputs.ec2_ip }}:${{ env.APP_DIR }}

        # SSH into EC2 and run Docker Compose
        ssh -i ~/.ssh/devops-key -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ steps.get-ec2-ip.outputs.ec2_ip }} << 'EOF'
          cd /opt/devops-blog/app
          cat <<EOV > .env
          PORT=3000
          MONGO_URI=${{ secrets.MONGO_URI }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        EOV
          sudo docker compose down || true
          sudo docker compose up -d --build
          sudo docker compose up -d
          echo "✅ App deployed successfully!"
        EOF