name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2
  EC2_USER: ubuntu
  APP_DIR: /opt/devops-blog
  TERRAFORM_DIR: ./terraform/docker-compose-ec2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ---------- Checkout code ----------
    - name: Checkout repository
      uses: actions/checkout@v3

    # ---------- Set up SSH key ----------
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/devops-key
        chmod 600 ~/.ssh/devops-key

    # ---------- Configure AWS ----------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: List Terraform folder
      run: ls -la ./terraform/docker-compose-ec2

    # ---------- Configure Terraform ----------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.13.4

    - name: Verify working directory
      run: pwd && ls -la ./terraform/docker-compose-ec2

    - name: Check Terraform version
      run: terraform version

    # ---------- Terraform Init & Apply ----------
    - name: Terraform Init
      run: terraform -chdir=./terraform/docker-compose-ec2 init

    - name: Terraform Apply
      run: terraform -chdir=./terraform/docker-compose-ec2 apply -auto-approve
      env:
        TF_VAR_region: ${{ vars.REGION }}
        TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        TF_VAR_mongo_uri: ${{ secrets.MONGO_URI }}
        TF_VAR_PORT: ${{ vars.PORT }}
        TF_VAR_devops_public_key: ${{ secrets.devops_public_key }}


    # ---------- Get EC2 Public IP ----------
    - name: Get EC2 public IP
      id: get-ec2-ip
      run: |
        EC2_IP=$(terraform -chdir=./terraform/docker-compose-ec2 output -raw public_ip 2>/dev/null | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n1)
        echo "ec2_ip=$EC2_IP" >> $GITHUB_OUTPUT

    # ---------- Deploy to EC2 ----------
    - name: Deploy app to EC2
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        PORT: 3000
      run: |
        echo "Deploying to ${{ steps.get-ec2-ip.outputs.ec2_ip }}"

        # Copy repo to EC2
        scp -o StrictHostKeyChecking=no -r . ${{ env.EC2_USER }}@${{ steps.get-ec2-ip.outputs.ec2_ip }}:${{ env.APP_DIR }}

        # SSH into EC2 and run Docker Compose
        ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ steps.get-ec2-ip.outputs.ec2_ip }} << 'EOF'
          cd $APP_DIR
          cat <<EOV > .env
          PORT=${PORT}
          MONGO_URI=${MONGO_URI}
          OPENAI_API_KEY=${OPENAI_API_KEY}
        EOV
          docker compose up -d --build
        EOF
