name: Terraform Destroy
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      TERRAFORM_DIR: ./terraform/docker-compose-ec2
      AWS_REGION: eu-west-2
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

            # ---------- Authenticate Terraform Cloud ----------
      - name: Authenticate to Terraform Cloud
        run: |
            mkdir -p ~/.terraform.d
            cat > ~/.terraform.d/credentials.tfrc.json <<EOF
            {
            "credentials": {
                "app.terraform.io": {
                "token": "${{ secrets.TF_API_TOKEN }}"
                }
            }
            }
            EOF

      - name: Terraform Init
        run: terraform -chdir=${{ env.TERRAFORM_DIR }} init

      - name: Terraform Destroy
        run: terraform -chdir=${{ env.TERRAFORM_DIR }} destroy -auto-approve
        env:
            TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
            TF_VAR_region: ${{ vars.REGION }}
            TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
            TF_VAR_mongo_uri: ${{ secrets.MONGO_URI }}
            TF_VAR_PORT: ${{ vars.PORT }}
            TF_VAR_devops_public_key: ${{ secrets.devops_public_key }}
